<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <script>

        // const promise1 = new Promise((resolve, reject) => {
        //     console.log('promise1')
        // })
        // console.log('1', promise1);
        // promise1
        // '1', promise1



        // const promise = new Promise((resolve, reject) => {
        //     console.log(1)
        //     resolve()
        //     console.log(2)
        // })
        // promise.then(() => {
        //     console.log(3)
        // })
        // console.log(4)
        // 1 2 4 3 


        // const promise = new Promise((resolve, reject) => {
        //     console.log(1);
        //     console.log(2);
        // });
        // promise.then(() => {
        //     console.log(3);
        // });
        // console.log(4);
        // 1 2 4



        // const promise1 = new Promise((resolve, reject) => {
        //     console.log('promise1')
        //     resolve('resolve1')
        // })
        // const promise2 = promise1.then(res => {
        //     console.log(res)
        // })
        // console.log('1', promise1);
        // console.log('2', promise2);

        // promise1
        // '1', promise1
        // '2', promise2
        // resolve1



        // const fn = () => (new Promise((resolve, reject) => {
        //     console.log(1);
        //     resolve('success')
        // }))
        // fn().then(res => {
        //     console.log(res)
        // })
        // console.log('start')
        // 1 start success


        // const fn = () =>
        //     new Promise((resolve, reject) => {
        //         console.log(1);
        //         resolve("success");
        //     });
        // console.log("start");
        // fn().then(res => {
        //     console.log(res);
        // });
        //start 1 success


        // console.log('start')
        // setTimeout(() => {
        //     console.log('time')
        // })
        // Promise.resolve().then(() => {
        //     console.log('resolve')
        // })
        // console.log('end')
        // start end resolve time



        // const promise = new Promise((resolve, reject) => {
        //     console.log(1);
        //     setTimeout(() => {
        //         console.log("timerStart");
        //         resolve("success");
        //         console.log("timerEnd");
        //     }, 0);
        //     console.log(2);
        // });
        // promise.then((res) => {
        //     console.log(res);
        // });
        // console.log(4);

        // 1 2 4 timerStart timerEnd success



        // setTimeout(() => {
        //     console.log('timer1');
        //     setTimeout(() => {
        //         console.log('timer3')
        //     }, 0)
        // }, 0)
        // setTimeout(() => {
        //     console.log('timer2')
        // }, 0)
        // console.log('start')

        // start timer1 timer2 timer3




        // setTimeout(() => {
        //     console.log('timer1');
        //     Promise.resolve().then(() => {
        //         console.log('promise')
        //     })
        // }, 0)
        // setTimeout(() => {
        //     console.log('timer2')
        // }, 0)
        // console.log('start')

        // start timer1 promise timer2



        // Promise.resolve().then(() => {
        //     console.log('promise1');
        //     const timer2 = setTimeout(() => {
        //         console.log('timer2')
        //     }, 0)
        // });
        // const timer1 = setTimeout(() => {
        //     console.log('timer1')
        //     Promise.resolve().then(() => {
        //         console.log('promise2')
        //     })
        // }, 0)
        // console.log('start');

        //start promise1 timer1 promise2 timer2


        // const promise1 = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         resolve('success')
        //     }, 1000)
        // })
        // const promise2 = promise1.then(() => {
        //     throw new Error('error!!!')
        // })

        // console.log('promise1', promise1)
        // console.log('promise2', promise2)
        // setTimeout(() => {
        //     console.log('promise1', promise1)
        //     console.log('promise2', promise2)
        // }, 2000)
        // promise1 success
        // promise2 'error!!!'
        // 'error!!!'
        // promise1 success
        // promise2 'error!!!'




        // const promise1 = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         resolve("success");
        //         console.log("timer1");
        //     }, 1000);
        //     console.log("promise1里的内容");
        // });
        // const promise2 = promise1.then(() => {
        //     throw new Error("error!!!");
        // });
        // console.log("promise1", promise1);
        // console.log("promise2", promise2);
        // setTimeout(() => {
        //     console.log("timer2");
        //     console.log("promise1", promise1);
        //     console.log("promise2", promise2);
        // }, 2000);

        // promise1里的内容
        //promise1 success 
        //promise2 error!!!
        //timer1
        //error!!!
        //timer2
        //promise1 success 
        //promise2 error!!!



        // const promise = new Promise((resolve, reject) => {
        //     resolve("success1");
        //     reject("error");
        //     resolve("success2");
        // });
        // promise
        //     .then(res => {
        //         console.log("then: ", res);
        //     }).catch(err => {
        //         console.log("catch: ", err);
        //     })

        //then success1



        // const promise = new Promise((resolve, reject) => {
        //     reject("error");
        //     resolve("success2");
        // });
        // promise
        //     .then(res => {
        //         console.log("then1: ", res);
        //     }).then(res => {
        //         console.log("then2: ", res);
        //     }).catch(err => {
        //         console.log("catch: ", err);
        //     }).then(res => {
        //         console.log("then3: ", res);
        //     })
        //carch:errr
        // then3:undefined





        // Promise.resolve(1)
        //     .then(res => {
        //         console.log(res);
        //         return 2;
        //     })
        //     .catch(err => {
        //         return 3;
        //     })
        //     .then(res => {
        //         console.log(res);
        //     });
        //1 2



        // Promise.reject(1)
        //     .then(res => {
        //         console.log(res);
        //         return 2;
        //     })
        //     .catch(err => {
        //         console.log(err);
        //         return 3
        //     })
        //     .then(res => {
        //         console.log(res);
        //     });
        // 1 3


        // const promise = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         console.log('timer')
        //         resolve('success')
        //     }, 1000)
        // })
        // const start = Date.now();
        // promise.then(res => {
        //     console.log(res, Date.now() - start)
        // })
        // promise.then(res => {
        //     console.log(res, Date.now() - start)
        // })

        //timerr
        //success 1004
        //success 1004




        // Promise.resolve().then(() => {
        //     return new Error('error!!!')
        // }).then(res => {
        //     console.log("then: ", res)
        // }).catch(err => {
        //     console.log("catch: ", err)
        // })
        //then error!!!



        // const promise = Promise.resolve().then(() => {
        //     return promise;
        // })
        // promise.catch(console.err)
        // Chaining cycle detected for promise #<Promise>.then 或 .catch 返回的值不能是 promise 本身，否则会造成死循环。



        // Promise.resolve(1)
        //     .then(2)
        //     .then(Promise.resolve(3))
        //     .then(console.log)
        //第一个then和第二个then中传入的都不是函数，一个是数字类型，一个是对象类型，因此发生了透传，将resolve(1) 的值直接传到最后一个then里。




        // Promise.reject('err!!!')
        //     .then((res) => {
        //         console.log('success', res)
        //     }, (err) => {
        //         console.log('error', err)
        //     }).catch(err => {
        //         console.log('catch', err)
        //     })
        //error err!!!




        // Promise.reject('error!!!')
        //     .then((res) => {
        //         console.log('success', res)
        //     }).catch(err => {
        //         console.log('catch', err)
        //     })
        // catch error!!!



        // Promise.resolve()
        //     .then(function success(res) {
        //         throw new Error('error!!!')
        //     }, function fail1(err) {
        //         console.log('fail1', err)
        //     }).catch(function fail2(err) {
        //         console.log('fail2', err)
        //     })
        // fail2 Error: error!!!at success





        // Promise.resolve('1')
        //     .then(res => {
        //         console.log(res)
        //     })
        //     .finally(() => {
        //         console.log('finally')
        //     })
        // Promise.resolve('2')
        //     .finally(() => {
        //         console.log('finally2')
        //         return '我是finally2返回的值'
        //     })
        //     .then(res => {
        //         console.log('finally2后面的then函数', res)
        //     })

        // '1'
        // 'finally2'
        // 'finally'
        // 'finally2后面的then函数' '2'




        // Promise.resolve('1')
        //     .finally(() => {
        //         console.log('finally1')
        //         throw new Error('我是finally中抛出的异常')
        //     })
        //     .then(res => {
        //         console.log('finally后面的then函数', res)
        //     })
        //     .catch(err => {
        //         console.log('捕获错误', err)
        //     })

        // finally1
        // 捕获错误 Error: 我是finally中抛出的异常
        // at 
        // at <anonymous>




        // function promise1() {
        //     let p = new Promise((resolve) => {
        //         console.log('promise1');
        //         resolve('1')
        //     })
        //     return p;
        // }
        // function promise2() {
        //     return new Promise((resolve, reject) => {
        //         reject('error')
        //     })
        // }
        // promise1()
        //     .then(res => console.log(res))
        //     .catch(err => console.log(err))
        //     .finally(() => console.log('finally1'))

        // promise2()
        //     .then(res => console.log(res))
        //     .catch(err => console.log(err))
        //     .finally(() => console.log('finally2'))

        //promise1
        //1
        //error
        //finally1
        //finally2



        // function promise1() {
        //     let p = new Promise((resolve) => {
        //         console.log('promise1');
        //         resolve('1')
        //     })
        //     return p;
        // }
        // function promise2() {
        //     return new Promise((resolve, reject) => {
        //         reject('error')
        //     })
        // }
        // promise1()
        //     .then(res => console.log(res))
        //     .catch(err => console.log(err))
        //     .then(() => console.log('finally1'))

        // promise2()
        //     .then(res => console.log(res))
        //     .catch(err => console.log(err))
        //     .then(() => console.log('finally2'))

        //promise1
        //1
        //finally2
        //error
        //finally1
            




        





        // var promise = new Promise(function (resolve, reject) {
        //     setTimeout(function () {
        //         resolve(1);
        //     }, 3000)
        // })
        // promise.then(() => {
        //     return Promise.resolve(2);
        // }).then((n) => {
        //     console.log(n)//2
        // });

        // promise.then(() => {
        //     return 2
        // }).then((n) => {
        //     console.log('r' + n)//2
        // });

        // promise.then(2).then((n) => {
        //     console.log(n)//1
        // });
        // 2 1 2


        // let a;
        // const b = new Promise((resolve, reject) => {
        //     console.log('promise1');
        //     resolve();
        // }).then(() => {
        //     console.log('promise2');
        // }).then(() => {
        //     console.log('promise3');
        // }).then(() => {
        //     console.log('promise4');
        // });

        // a = new Promise(async (resolve, reject) => {
        //     console.log(a);
        //     await b;
        //     console.log(a);
        //     console.log('after1');
        //     await a
        //     resolve(true);
        //     console.log('after2');
        // });
        // console.log('end');

        // promise1
        // undefined
        // end
        // promise2
        // promise3
        // promise4
        // Promise
        // after1


    </script>
</body>

</html>